# Generated by Django 2.1.5 on 2019-03-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('image_url', models.URLField(help_text='轮播图url', verbose_name='轮播图url')),
                ('priority', models.IntegerField(help_text='优先级', verbose_name='优先级')),
            ],
            options={
                'verbose_name': '轮播图',
                'db_table': 'tb_banner',
                'verbose_name_plural': '轮播图',
                'ordering': ['priority', '-update_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('content', models.TextField(help_text='内容', verbose_name='内容')),
            ],
            options={
                'verbose_name': '评论',
                'db_table': 'tb_comments',
                'verbose_name_plural': '评论',
                'ordering': ['-update_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HotNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('priority', models.IntegerField(help_text='优先级', verbose_name='优先级')),
            ],
            options={
                'verbose_name': '热门新闻',
                'db_table': 'tb_hotnews',
                'verbose_name_plural': '热门新闻',
                'ordering': ['-update_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('title', models.CharField(help_text='标题', max_length=150, verbose_name='标题')),
                ('digest', models.CharField(help_text='摘要', max_length=200, verbose_name='摘要')),
                ('content', models.TextField(help_text='内容', verbose_name='内容')),
                ('clicks', models.IntegerField(default=0, help_text='点击量', verbose_name='点击量')),
                ('image_url', models.URLField(default='', help_text='图片url', verbose_name='图片url')),
            ],
            options={
                'verbose_name': '新闻',
                'db_table': 'tb_news',
                'verbose_name_plural': '新闻',
                'ordering': ['-update_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('name', models.CharField(help_text='标签名', max_length=64, verbose_name='标签名')),
            ],
            options={
                'verbose_name': '新闻标签',
                'db_table': 'tb_tag',
                'verbose_name_plural': '新闻标签',
                'ordering': ['-update_time', '-id'],
            },
        ),
    ]
