# Generated by Django 2.1.7 on 2019-03-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.FloatField(default=0.0, help_text='课程时长', verbose_name='课程时长'),
        ),
    ]
